export const ROLES = {
  ADMIN: "ADMIN",
  PRESIDENT: "PRESIDENT",
  VICE_PRESIDENT: "VICE_PRESIDENT",
  STAFF: "STAFF",
  MEMBER: "MEMBER",
};

export const STATUSES = {
  PENDING: "PENDING",
  ACCEPTED: "ACCEPTED",
  REJECTED: "REJECTED",
};

export const CHANNEL_TYPES = {
  GENERAL: "GENERAL",
  STAFF: "STAFF",
  GLOBAL_STAFF: "GLOBAL_STAFF",
  ADMIN_PRESIDENT: "ADMIN_PRESIDENT",
  GLOBAL_PRESIDENTS: "GLOBAL_PRESIDENTS",
  CUSTOM: "CUSTOM",
};

export const CHANNEL_KEYS = {
  GLOBAL_STAFF: "GLOBAL_STAFF",
  GLOBAL_PRESIDENTS: "GLOBAL_PRESIDENTS",
};

export const POST_TYPES = {
  EVENT: "EVENT",
  ANNOUNCEMENT: "ANNOUNCEMENT",
  DISCUSSION: "DISCUSSION",
};

export const POST_STATUSES = {
  PENDING: "PENDING",
  PUBLISHED: "PUBLISHED",
  REJECTED: "REJECTED",
};

export const STAFF_ROLES = [ROLES.ADMIN, ROLES.PRESIDENT, ROLES.VICE_PRESIDENT, ROLES.STAFF];
export const CLUB_OFFICE_ROLES = [ROLES.PRESIDENT, ROLES.VICE_PRESIDENT, ROLES.STAFF];
